services:
  - type: web
    name: sucreshop
    env: python
    buildCommand: pip install -r backend/requirements.txt && cd frontend && npm install && npm run build
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: SUPABASE_URL
        fromDatabase:
          name: supabase-db
          property: connectionString
      - key: SUPABASE_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true